package main

import (
	"github.com/clicksend-rest-api-v3/mcp-server/config"
	"github.com/clicksend-rest-api-v3/mcp-server/models"
	tools_email_to_sms_stripped_strings "github.com/clicksend-rest-api-v3/mcp-server/tools/email_to_sms_stripped_strings"
	tools_contact_lists "github.com/clicksend-rest-api-v3/mcp-server/tools/contact_lists"
	tools_automation_rules "github.com/clicksend-rest-api-v3/mcp-server/tools/automation_rules"
	tools_email_marketing "github.com/clicksend-rest-api-v3/mcp-server/tools/email_marketing"
	tools_subaccounts "github.com/clicksend-rest-api-v3/mcp-server/tools/subaccounts"
	tools_mms "github.com/clicksend-rest-api-v3/mcp-server/tools/mms"
	tools_sms "github.com/clicksend-rest-api-v3/mcp-server/tools/sms"
	tools_voice "github.com/clicksend-rest-api-v3/mcp-server/tools/voice"
	tools_sms_campaigns "github.com/clicksend-rest-api-v3/mcp-server/tools/sms_campaigns"
	tools_reseller_accounts "github.com/clicksend-rest-api-v3/mcp-server/tools/reseller_accounts"
	tools_statistics "github.com/clicksend-rest-api-v3/mcp-server/tools/statistics"
	tools_account "github.com/clicksend-rest-api-v3/mcp-server/tools/account"
	tools_numbers "github.com/clicksend-rest-api-v3/mcp-server/tools/numbers"
	tools_contacts "github.com/clicksend-rest-api-v3/mcp-server/tools/contacts"
	tools_transactional_email "github.com/clicksend-rest-api-v3/mcp-server/tools/transactional_email"
	tools_email_to_sms_allowed_address "github.com/clicksend-rest-api-v3/mcp-server/tools/email_to_sms_allowed_address"
	tools_account_recharge "github.com/clicksend-rest-api-v3/mcp-server/tools/account_recharge"
	tools_fax "github.com/clicksend-rest-api-v3/mcp-server/tools/fax"
	tools_sms_templates "github.com/clicksend-rest-api-v3/mcp-server/tools/sms_templates"
	tools_referral_accounts "github.com/clicksend-rest-api-v3/mcp-server/tools/referral_accounts"
	tools_post_letter "github.com/clicksend-rest-api-v3/mcp-server/tools/post_letter"
	tools_post_direct_mail "github.com/clicksend-rest-api-v3/mcp-server/tools/post_direct_mail"
	tools_delivery_issues "github.com/clicksend-rest-api-v3/mcp-server/tools/delivery_issues"
	tools_reseller "github.com/clicksend-rest-api-v3/mcp-server/tools/reseller"
	tools_forgot_account "github.com/clicksend-rest-api-v3/mcp-server/tools/forgot_account"
	tools_postcards "github.com/clicksend-rest-api-v3/mcp-server/tools/postcards"
	tools_countries "github.com/clicksend-rest-api-v3/mcp-server/tools/countries"
	tools_timezones "github.com/clicksend-rest-api-v3/mcp-server/tools/timezones"
	tools_contact_suggestions "github.com/clicksend-rest-api-v3/mcp-server/tools/contact_suggestions"
	tools_uploads "github.com/clicksend-rest-api-v3/mcp-server/tools/uploads"
	tools_search "github.com/clicksend-rest-api-v3/mcp-server/tools/search"
	tools_pricing "github.com/clicksend-rest-api-v3/mcp-server/tools/pricing"
	tools_sdk "github.com/clicksend-rest-api-v3/mcp-server/tools/sdk"
	tools_post_address_detection "github.com/clicksend-rest-api-v3/mcp-server/tools/post_address_detection"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_email_to_sms_stripped_strings.CreateListstrippedstringsTool(cfg),
		tools_email_to_sms_stripped_strings.CreateCreatestrippedstringTool(cfg),
		tools_contact_lists.CreateRemoveduplicatecontactsTool(cfg),
		tools_email_to_sms_stripped_strings.CreateDeletestrippedstringTool(cfg),
		tools_email_to_sms_stripped_strings.CreateFindspecificstrippedstringTool(cfg),
		tools_email_to_sms_stripped_strings.CreateUpdatestrippedstringTool(cfg),
		tools_automation_rules.CreateListrulesTool(cfg),
		tools_automation_rules.CreateCreateanewruleTool(cfg),
		tools_email_marketing.CreateGetallmastertemplatecategoriesTool(cfg),
		tools_subaccounts.CreateCreateanewsubaccountTool(cfg),
		tools_subaccounts.CreateGetallsubaccountsTool(cfg),
		tools_mms.CreateExportmmshistoryTool(cfg),
		tools_sms.CreateSendansmsTool(cfg),
		tools_email_marketing.CreateGetspecificmastertemplateTool(cfg),
		tools_voice.CreateExportvoicehistoryTool(cfg),
		tools_sms_campaigns.CreateLinktrackingexportTool(cfg),
		tools_reseller_accounts.CreateCreatereselleraccount_publicTool(cfg),
		tools_statistics.CreateGetvoicestatisticsTool(cfg),
		tools_account.CreateSendaccountactivationtokenTool(cfg),
		tools_voice.CreateGetvoicehistoryTool(cfg),
		tools_numbers.CreateGetalldedicatednumbersTool(cfg),
		tools_contacts.CreateGetallcontactsinalistTool(cfg),
		tools_contacts.CreateCreateanewcontactTool(cfg),
		tools_email_marketing.CreateGetallemailcampaignsTool(cfg),
		tools_automation_rules.CreateGet_automations_fax_inbound_inbound_rule_idTool(cfg),
		tools_automation_rules.CreatePut_automations_fax_inbound_inbound_rule_idTool(cfg),
		tools_automation_rules.CreateDelete_automations_fax_inbound_inbound_rule_idTool(cfg),
		tools_transactional_email.CreateExporthistoryTool(cfg),
		tools_email_to_sms_allowed_address.CreateListofemail_to_smsallowedaddressTool(cfg),
		tools_email_to_sms_allowed_address.CreateCreateemailtosmsallowedaddressTool(cfg),
		tools_contacts.CreateTransferacontactTool(cfg),
		tools_email_marketing.CreateGetspecificemailcampaignhistoryTool(cfg),
		tools_account_recharge.CreatePurchaseapackageTool(cfg),
		tools_fax.CreateListoffaxdeliveryreceiptsTool(cfg),
		tools_fax.CreateAddatestdeliveryreceiptTool(cfg),
		tools_fax.CreateSendfaxTool(cfg),
		tools_sms.CreateGetaspecificdeliveryreceiptTool(cfg),
		tools_sms_templates.CreateListoftemplatesTool(cfg),
		tools_sms_templates.CreateCreateatemplateTool(cfg),
		tools_voice.CreateGetvoicereceiptsTool(cfg),
		tools_voice.CreatePost_voice_receiptsTool(cfg),
		tools_referral_accounts.CreateGetlistofreferralaccountsTool(cfg),
		tools_email_marketing.CreateGetallmasteremailtemplatesTool(cfg),
		tools_post_letter.CreatePost_post_letters_priceTool(cfg),
		tools_sms.CreateGetspecificinbound_pullTool(cfg),
		tools_contact_lists.CreateUpdateaspecificcontactlistTool(cfg),
		tools_contact_lists.CreateDeleteaspecificcontactlistTool(cfg),
		tools_contact_lists.CreateGetaspecificcontactlistTool(cfg),
		tools_post_direct_mail.CreateCalculatedirectmailcampaignpriceTool(cfg),
		tools_mms.CreateGetalldeliveryreceiptsTool(cfg),
		tools_email_marketing.CreateGetalltemplatesforcategoryTool(cfg),
		tools_sms.CreateGetallhistoryTool(cfg),
		tools_transactional_email.CreateEmailpriceTool(cfg),
		tools_automation_rules.CreateDeletearuleTool(cfg),
		tools_automation_rules.CreateGetaspecificruleTool(cfg),
		tools_automation_rules.CreateUpdatearuleTool(cfg),
		tools_sms.CreateExportsmshistoryTool(cfg),
		tools_delivery_issues.CreateGetdeliveryissuesTool(cfg),
		tools_delivery_issues.CreateCreatedeliveryissueTool(cfg),
		tools_reseller.CreateResellerbysubdomainTool(cfg),
		tools_subaccounts.CreateDeleteaspecificsubaccountTool(cfg),
		tools_subaccounts.CreateGetaspecificsubaccountTool(cfg),
		tools_subaccounts.CreateUpdateaspecificsubaccountTool(cfg),
		tools_sms.CreateMarkallinboundsmsasreadTool(cfg),
		tools_automation_rules.CreateDelete_automations_sms_receipts_receipt_rule_idTool(cfg),
		tools_automation_rules.CreateGet_automations_sms_receipts_receipt_rule_idTool(cfg),
		tools_automation_rules.CreatePut_automations_sms_receipts_receipt_rule_idTool(cfg),
		tools_mms.CreateGetdeliveryreceiptTool(cfg),
		tools_sms_campaigns.CreateGetlistofsmscampaignsTool(cfg),
		tools_account_recharge.CreateGettransactionsTool(cfg),
		tools_email_marketing.CreateDeleteemailtemplateTool(cfg),
		tools_email_marketing.CreateGetspecificemailtemplateTool(cfg),
		tools_email_marketing.CreateUpdateanemailtemplateTool(cfg),
		tools_post_letter.CreateExportpostletterhistoryTool(cfg),
		tools_reseller_accounts.CreateTransfercreditTool(cfg),
		tools_transactional_email.CreateEmailsendTool(cfg),
		tools_sms_templates.CreateDeleteatemplateTool(cfg),
		tools_sms_templates.CreateUpdateatemplateTool(cfg),
		tools_email_marketing.CreateSendverificationtokenTool(cfg),
		tools_email_marketing.CreateGetallallowedemailaddressesTool(cfg),
		tools_email_marketing.CreateCreateallowedemailaddressTool(cfg),
		tools_automation_rules.CreateUpdatearuleTool(cfg),
		tools_automation_rules.CreateDeletearuleTool(cfg),
		tools_automation_rules.CreateGetaspecificruleTool(cfg),
		tools_account_recharge.CreateListofpackagesTool(cfg),
		tools_contact_lists.CreateGetlistofacceptableimportfieldsTool(cfg),
		tools_account.CreateVerifynewaccountTool(cfg),
		tools_automation_rules.CreateGet_automations_fax_inboundTool(cfg),
		tools_automation_rules.CreatePost_automations_fax_inboundTool(cfg),
		tools_forgot_account.CreateForgotusernameTool(cfg),
		tools_postcards.CreateExportpostcardhistoryTool(cfg),
		tools_post_letter.CreateUpdatepostreturnaddressTool(cfg),
		tools_post_letter.CreateDeletepostreturnaddressTool(cfg),
		tools_post_letter.CreateGetpostreturnaddressTool(cfg),
		tools_email_marketing.CreateVerifyallowedemailaddressTool(cfg),
		tools_contact_lists.CreateExportcontactslistTool(cfg),
		tools_mms.CreateMarkreceiptsasreadTool(cfg),
		tools_automation_rules.CreatePost_automations_voice_receiptsTool(cfg),
		tools_automation_rules.CreateGet_automations_voice_receiptsTool(cfg),
		tools_sms_campaigns.CreateCancelansmscampaignTool(cfg),
		tools_countries.CreateGetallcountriesTool(cfg),
		tools_mms.CreateGetpriceTool(cfg),
		tools_fax.CreateExportfaxhistoryTool(cfg),
		tools_account.CreateGetaccountTool(cfg),
		tools_account.CreateCreateanewaccountTool(cfg),
		tools_account.CreateUpdateaccountTool(cfg),
		tools_account_recharge.CreateUpdatecreditcardinfoTool(cfg),
		tools_account_recharge.CreateGetcreditcardinfoTool(cfg),
		tools_postcards.CreateSendpostcardTool(cfg),
		tools_reseller.CreateUpdateresellersettingTool(cfg),
		tools_reseller.CreateGetresellersettingTool(cfg),
		tools_sms.CreateMarkdeliveryreceiptsasreadTool(cfg),
		tools_email_marketing.CreateGetallemailtemplatesTool(cfg),
		tools_email_marketing.CreateCreatenewemailtemplatefrommastertemplateTool(cfg),
		tools_sms_campaigns.CreateLinkstatisticsTool(cfg),
		tools_contact_lists.CreateImportcontactstolistTool(cfg),
		tools_transactional_email.CreatePost_email_receiptsTool(cfg),
		tools_fax.CreateGetfaxhistoryTool(cfg),
		tools_statistics.CreateGetsmsstatisticsTool(cfg),
		tools_email_to_sms_allowed_address.CreateDeleteemail_to_smsallowedaddressTool(cfg),
		tools_email_to_sms_allowed_address.CreateGetspecificemail_to_smsallowedaddressTool(cfg),
		tools_email_to_sms_allowed_address.CreateUpdateemail_to_smsallowedaddressTool(cfg),
		tools_timezones.CreateGettimezonesTool(cfg),
		tools_sms.CreateCancelallscheduledmessagesTool(cfg),
		tools_sms_campaigns.CreateCalculatepriceforsmscampaignTool(cfg),
		tools_contacts.CreateRemoveoptedoutcontactsTool(cfg),
		tools_voice.CreateMarkedvoicereceiptsasreadTool(cfg),
		tools_email_marketing.CreateGetspecificemailtemplatecategoryTool(cfg),
		tools_subaccounts.CreateRegenerateapikeyTool(cfg),
		tools_postcards.CreateGetpostcardhistoryTool(cfg),
		tools_sms.CreateGetallinboundsms_pullTool(cfg),
		tools_sms.CreateAddatestinboundsmsTool(cfg),
		tools_postcards.CreateCalculatepricingTool(cfg),
		tools_fax.CreatePost_fax_priceTool(cfg),
		tools_contacts.CreateDeleteaspecificcontactTool(cfg),
		tools_contacts.CreateGetaspecificcontactTool(cfg),
		tools_contacts.CreateUpdateaspecificcontactTool(cfg),
		tools_sms_campaigns.CreateUseshorturlTool(cfg),
		tools_post_letter.CreateSendpostletterTool(cfg),
		tools_sms.CreatePost_sms_priceTool(cfg),
		tools_reseller_accounts.CreateGetreselleraccountTool(cfg),
		tools_reseller_accounts.CreateUpdatereselleraccountTool(cfg),
		tools_numbers.CreateSearchdedicatednumbersbycountryTool(cfg),
		tools_contact_suggestions.CreateListcontactsuggestionsTool(cfg),
		tools_uploads.CreateUploadafileTool(cfg),
		tools_email_marketing.CreateGetspecificemailcampaignTool(cfg),
		tools_email_marketing.CreateUpdateemailcampaignTool(cfg),
		tools_voice.CreateGetspecificvoicereceiptTool(cfg),
		tools_email_marketing.CreateCancelemailcampaignTool(cfg),
		tools_mms.CreateCancelallmmsTool(cfg),
		tools_voice.CreateCancelallvoicecallsTool(cfg),
		tools_email_marketing.CreateDeleteallowedemailaddressTool(cfg),
		tools_email_marketing.CreateGetspecificallowedemailaddressTool(cfg),
		tools_forgot_account.CreateForgotpasswordTool(cfg),
		tools_post_direct_mail.CreateListdirectmailcampaignsTool(cfg),
		tools_email_marketing.CreateCalculatepriceTool(cfg),
		tools_search.CreateSearchcontacts_listsTool(cfg),
		tools_mms.CreateGetmmshistoryTool(cfg),
		tools_forgot_account.CreateVerifyforgotpasswordTool(cfg),
		tools_email_marketing.CreateUploadimagetospecifictemplateTool(cfg),
		tools_automation_rules.CreateListrulesTool(cfg),
		tools_contact_lists.CreateShowcsvimportfilepreviewTool(cfg),
		tools_sms.CreateCancelascheduledmessageTool(cfg),
		tools_automation_rules.CreateCreateanewruleTool(cfg),
		tools_email_marketing.CreateCreateemailcampaignTool(cfg),
		tools_post_letter.CreateGetlistofpostreturnaddressesTool(cfg),
		tools_post_letter.CreateCreateapostreturnaddressTool(cfg),
		tools_account.CreateAccountusageTool(cfg),
		tools_automation_rules.CreateGet_automations_email_receiptTool(cfg),
		tools_automation_rules.CreatePost_automations_email_receiptTool(cfg),
		tools_automation_rules.CreatePut_automations_email_receipt_rule_idTool(cfg),
		tools_automation_rules.CreateDelete_automations_email_receipt_rule_idTool(cfg),
		tools_automation_rules.CreateGet_automations_email_receipt_rule_idTool(cfg),
		tools_contact_lists.CreateGetallcontactlistsTool(cfg),
		tools_contact_lists.CreateCreateanewcontactlistTool(cfg),
		tools_pricing.CreateGetcountrypricingTool(cfg),
		tools_fax.CreateGetaspecificfaxdeliveryreceiptTool(cfg),
		tools_post_direct_mail.CreateSearchlocationsTool(cfg),
		tools_mms.CreateCancelmmsTool(cfg),
		tools_sms_campaigns.CreateGetsmscampaignTool(cfg),
		tools_sms_campaigns.CreateUpdateansmscampaignTool(cfg),
		tools_automation_rules.CreateGet_automations_sms_receiptsTool(cfg),
		tools_automation_rules.CreatePost_automations_sms_receiptsTool(cfg),
		tools_sms.CreateGet_sms_receiptsTool(cfg),
		tools_sms.CreatePost_sms_receiptsTool(cfg),
		tools_voice.CreateVoicelanguagesTool(cfg),
		tools_post_direct_mail.CreateCreatenewcampaignTool(cfg),
		tools_sms.CreateMarkaspecificinboundsmsasreadTool(cfg),
		tools_voice.CreateCancelaspecificvoicecallTool(cfg),
		tools_post_letter.CreateGetpostletterhistoryTool(cfg),
		tools_numbers.CreateBuydedicatednumberTool(cfg),
		tools_transactional_email.CreateEmailhistoryTool(cfg),
		tools_sms_campaigns.CreateLinktrackingTool(cfg),
		tools_fax.CreateMarkfaxdeliveryreceiptsasreadTool(cfg),
		tools_voice.CreateSendavoicecallTool(cfg),
		tools_sdk.CreateSdkdownloadTool(cfg),
		tools_post_address_detection.CreateDetectaddressTool(cfg),
		tools_mms.CreateSendmmsTool(cfg),
		tools_voice.CreatePost_voice_priceTool(cfg),
		tools_automation_rules.CreateDelete_automations_voice_receipts_receipt_rule_idTool(cfg),
		tools_automation_rules.CreateGet_automations_voice_receipts_receipt_rule_idTool(cfg),
		tools_automation_rules.CreatePut_automations_voice_receipts_receipt_rule_idTool(cfg),
		tools_reseller_accounts.CreateCreatereselleraccountTool(cfg),
		tools_reseller_accounts.CreateListofreselleraccountsTool(cfg),
	}
}
